name: My Workflow2

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        echo "A initial message"
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        subfinder -d baidu.com 
        echo "Another message or command"
        python myscript.py
        bash some-shell-script-file.sh -xe
     - run: echo "One last message"
