name: My Workflow5

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        echo "A initial message"
         [ ! -x /home/runner/go/bin/subfinder ] && go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
        subfinder -d baidu.com 
        echo "Another message or command"
     - run: echo "One last message"
